# Generated by Django 3.2.5 on 2021-12-08 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variableIncome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationimporterloger',
            options={'managed': True, 'ordering': ('-updatedat',)},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='initial_price',
            field=models.FloatField(default=0.0, verbose_name='Cotação dia da recomendação'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='rating',
            field=models.CharField(choices=[('COMPRA', 'COMPRA'), ('VENDA', 'VENDA'), ('NEUTRO', 'NEUTRO')], max_length=30, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommendations', to='variableIncome.stock', verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='target',
            field=models.FloatField(default=0.0, verbose_name='Preço Alvo'),
        ),
        migrations.AlterField(
            model_name='research',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticket',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
