# Generated by Django 3.2.5 on 2021-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variableIncome', '0002_auto_20211208_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='dateinitial',
        ),
        migrations.AddField(
            model_name='recommendationimporterloger',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='research',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
