# Generated by Django 3.2.5 on 2022-03-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variableIncome', '0003_auto_20211217_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='rating',
            field=models.CharField(choices=[('COMPRA', 'COMPRA'), ('VENDA', 'VENDA'), ('NEUTRO', 'NEUTRO'), ('REVISAO', 'SOB REVISÃO')], max_length=30, verbose_name='Rating'),
        ),
    ]
